name: Build Theos Tweak

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git make perl clang python3 libplist-utils fakeroot
          # Install ldid manually
          git clone https://github.com/ProcursusTeam/ldid.git
          cd ldid
          sudo make install
          cd ..

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "export THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build tweak
        run: |
          export THEOS=$HOME/theos
          make package

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-deb
          path: packages/*.deb
